export const Power = [
    section1 = {
        heading: 'Power Amplifier',
        desc: "Sdyn's Power Amplifiers use compact and extremely efficient power modules. These help to amplify the small electrical signal from the Vibration Controller to a proportionally high voltage and high current output, that is ideal to drive the shaker. The design of the Power Amplifier ensures energy and space. DSA series Power Amplifier use solid-state power devices in a Class-D Full Bridge configuration. They are digitally modulated with a high frequency pulse width modulated signal with efficiency of over 92%. Their modular construction makes them easy to handle and arrange for maximum output power with direct coupling to any resistive or inductive load. Integral air cooled design ensures continuous duty cycle without sacrificing performance at peak temperature and humidity.   These Power Amplifiers are compatible with any make of Electrodynamic Shakers and are designed to provide continuous rated voltage and current at high ambient temperature and humidity. A low knee filter provides smooth output, while removing switching noise and electromagnetic interference. A zobel network is dedicated for impedance matching over a wide range of frequencies for inductive loads. Adjustable current limit is also provided for controlling maximum output power so that accidents can be avoided.   Assembled in industry standard modular racks, all modules of our Power Amplifier are rack mountable. Removing and installing modules is made easy via guide rails on which every module is designed to slide. Designed to meet international design and safety standards, every module of our Power Amplifier is feature rich and contains its own power entry, power filtering, error indication and EMI conforming systems. Continuous upgrade of technology to better meet the international standards and reduce the carbon footprint of our system is a never-ending process at Sdyn. Through our various training, services and maintenance programs, we keep our customers updated with the latest product offerings and upgrades.   Major Sub Systems of the Power Amplifier are:",
        first: {
            heading: 'Digital Logic Unit',
            desc: "The microcontroller based Digital Logic Unit (DLU) controls and monitors the system features and safety interlocks of the DSA series Power Amplifier. The logic unit acts as a user friendly interface between the user and the equipment and can be operated both in manual and auto modes.   System parameters and trip interlocks are displayed on the alphanumeric display of the feather touch membrane keyboard front panel. Soft start and controlled shut down is offered with an online key on the front panel.   Shaker and amplifier safety interlocks are monitored and indicated on the front panel through a microcontroller chip. Interlock signals are routed through isolators and buffer network for proper latching and to prevent false triggering.   The signals are latched on to the fault analysis section of the microcontroller. Only after all faults are resolved, the system is allowed to go Online and increase the gain. Major system interlocks associated with DSA series of amplifier are over current, field fail, displacement limit, cooling shaker, over temperature, etc.",
            src1: "DLU Front",
            src2: "DLU Back",
        },
        second: {
            shead: "Major Sub Systems of the Digital Logic Unit are:",
            head1: {
                heading : "Internal Oscillator",
                desc : "The internal oscillator is a feature provided in the DLU for manual mode of operations wherein the g level is not controlled. The output of the internal oscillator is a pure sine wave. Its gain is controlled via the feather touch membrane keyboard front panel. Output voltage, current and frequency are displayed on the alphanumeric display.  The oscillator is capable of producing sine wave from 1Hz to 10kHz.", 
            },
            head2: {
                heading : "Signal Source Selection",
                desc : "As the DLU can generate its own sine signal in addition to the external signal from a Vibration Controller, it features a signal source selection that allows users to seamlessly switch between internal and external signal source using the feather touch membrane keyboard front panel. The selectable signal path offers negligible resistance and ensures signal integrity.",
            },
            head3: {
                heading : "Gain Control",
                desc : "The highly integrated gain control block of the DLU is designed using a digital potentiometer. All changes in gain are made gradually, one step at a time, to prevent any spike or sudden movement of the armature. Clamp and release operation is done automatically by the microcontroller inside the DLU based upon various inputs from the user and the interlocks.",
            },
            head4: {
                heading : "Auto Centring",
                desc : "All shakers from Sdyn have dynamic auto centring except SEV 125 and SEV 140, which features a mechanical only auto centring. Models SEV 180 to SEV 760 feature a combination of pneumatic + DC bias based auto centring. The mechanical axial stiffness of these models is nearly negligible. A displacement sensor is used calculate the exact position of armature in real-time. Based on this data, a digital control loop utilises air diaphragm and bellows for pneumatic auto centring and an analog control loop utilises DC bias for the Power Modules for DC bias auto centring.",
            },
        }
    },
    section2 = {
        heading: "Power Amplifier Remote",
        desc: "Power Amplifier Remote is provided as a separate module for applications that require remote control of the Power Amplifier and monitoring of all parameters and interlocks on a PC. This feature completely replicates the functionality of the LCD screen and the feather touch membrane keyboard on the Power Amplifier on the PC. It provides customers with the capability to control and monitor the following:",
        ldesc: {
            heading: 'System Controls',
            li1: 'Shaker Field',
            li2: 'Shaker Cooling',
            li3: 'Reset',
            li4: 'Online',
            li5: 'Amplifier Gain',
        },
        rdesc: {
            heading: 'System Parameters',
            li1: 'Output Voltage',
            li2: 'Output Current',
            li3: 'Amplifier Temperature',
            li4: 'Shaker Temperature',
            li5: 'Gain',
        },
        src: "",
        shead: "The remote application interfaces with the DLU via the following options:",
        li1: "RS232 for low end application with distances up to 25 meters",
        li2: "RS485 for high end application with distances up to 1 kilometre",
        descpost: "The system is designed on robust and versatile HEX command based protocol stack. It takes account of the start-up and shut-down sequence and does not allow user to input conflicting data. Associated cables and accessories are provided along with the application.",
    },
    section3 = {
        heading: "Power Module",
        desc: "The high power density and efficiency of the Power Modules of DSA series Power Amplifier is the heart of the system. These modules can use MOSFETs or IGBTs as their primary switching devices and can be coupled with numerous types of loads varying from resistive to inductive. As they are designed in a Class-D Full Bridge configuration, their operation is very similar to that of a buck converter. At output voltages lower than the input voltage, output current can be higher than the input current, as long as the input power is equal to the sum of output power and losses.  Every power module is rack mounted and features a wire free design implemented using copper bus bars instead of wires. This ensures that our power module never faces any issues pertaining to loose or damaged connection.  Each power module of the DSA series has a built-in PWM generation and management. These modules are stacked in master slave configuration for their parallel operation in the amplifier. PWM in paralleled modules is synchronised through master clock and a current feedback network is also implemented for precise current sharing amongst modules. Three-sigma design ensures peak current capability for continuous random operation, without affecting the life of the power device.",
        src1: "40kVA Front",
        src2: "40kVA Back",
        src3: "8kVA Front",
        src4: "8kVA Back",
        shead: "Major Sub Systems of the Power Module are:",
        first : {
            heading: "Driver Section",
            desc: "Driver section of the Power Module provides the necessary gate pulse to switch the conduction state of power devices from on to off and vice versa. A galvanic isolation-based gate driver circuit provides gate signals with negligible propagation and time delays. The final stage of the driver has a totem pole circuit in push-pull configuration for fast charging and discharging of the gate capacitances of the power devices at high frequencies.  In a multiple module system, one module is master and the rest are slaves. The driver section of the master module generates the clock that is followed by every module in that system. This syncs all the PWM signals and reduces the final output ripple. The driver section also has two feedback networks. First is a voltage feedback to ensure output waveform is proportional to input waveform. Second is a current feedback to ensure equal current is drawn from every module in a system.",
        },
        second : {
            heading: "Power Section",
            desc: "We are connected in full bridge configuration and mounted on a common heat sink. The integral cooling fans ensure safe thermal operation.  Each half of the bridge switches at modulated frequency such that the duty cycle varies at input signal rate. Each side is driven out of phase so that an amplified PWM signal appears across the bridge output.  An array of heat sensors and two dedicated current sensors ensure the safety of this section. They are factory set to respond to the absolute maximum limits of the devices to ensure their safety in the event of a malfunction.",
            src: "",
        },
        third : {
            heading: "Feedback Section",
            desc: "Voltage feedback from the output terminal of the power section (within the output filter) to the PWM controller makes a flat response Power Amplifier. The loop incorporates DC and high frequency derivative feedback. An integrator in the loop provides linear gain and low harmonic distortion. Overall current of the power module is sensed by a non-contacting sensor which is used for the purpose of tripping and current sharing.",
        },
        fourth : {
            heading: "Filter Section",
            desc: "Sufficient attenuation to high frequency is done by LC filters to get a pure amplified output. The major part is a combination of inductor and low ESR high frequency capacitors. The final stage of the filter section contains capacitor network for minimising any noise and electromagnetic interferences along with the zobel network for impedance matching.",
        },
    },
    section3 = {
        heading: "HVDC Section",
        desc: "The Power Amplifiers run on a widely acceptable range of 3-phase mains input and does not require any special operating environment or support equipment. Step-down 3-phase AC output of highly efficient vacuum impregnated transformer is rectified using three phase bridge rectifiers. Bridge rectifiers of single body construction are used for space saving and good heat sinking characteristics, alongside high voltage capacitors to suppress transients and minimise mains ripple. Different protection circuits are coupled at various stages for synchronisation. Single Phase Preventer is used at the 3-phase input, which senses any phase loss and any imbalance in 3-phase line voltage through phase synchronisation relay. It also displays the phase status on the Digital Logic Unit.",
    },
    section4 = {
        heading: "Technical Specifications",
        table1 : {
            shead: 'Power Amplifier',
            table_heading: {
                head1: 'Shaker Model',
                head2: 'Amplifier Model',
                head3: 'System Rating',
                head4: 'Power Output',
            },
            shead1 : 'Air Cooled Series',
            System : [
                {
                    Shaker_Model : 'SEV 125',
                    Amplifier_Model : 'DSA 1K',
                    System_Rating : '100 kgf',
                    Power_Output : '1 kVA',
                },
                {
                    Shaker_Model : 'SEV 125',
                    Amplifier_Model : 'DSA 1.5K',
                    System_Rating : '150 kgf',
                    Power_Output : '1.5 kVA',
                },
                {
                    Shaker_Model : 'SEV 140',
                    Amplifier_Model : 'DSA 2K',
                    System_Rating : '200 kgf',
                    Power_Output : '2 kVA',
                },
                {
                    Shaker_Model : 'SEV 140',
                    Amplifier_Model : 'DSA 3K',
                    System_Rating : '300 kgf',
                    Power_Output : '3 kVA',
                },
                {
                    Shaker_Model : 'SEV 180',
                    Amplifier_Model : 'DSA 4K',
                    System_Rating : '400 kgf',
                    Power_Output : '4 kVA',
                },
                {
                    Shaker_Model : 'SEV 180',
                    Amplifier_Model : 'DSA 6K',
                    System_Rating : '600 kgf',
                    Power_Output : '6 kVA',
                },
                {
                    Shaker_Model : 'SEV 240',
                    Amplifier_Model : 'DSA 10K',
                    System_Rating : '1000 kgf',
                    Power_Output : '10 kVA',
                },
                {
                    Shaker_Model : 'SEV 240',
                    Amplifier_Model : 'DSA 15K',
                    System_Rating : '1500 kgf',
                    Power_Output : '15 kVA',
                },
                {
                    Shaker_Model : 'SEV 300',
                    Amplifier_Model : 'DSA 24K',
                    System_Rating : '2000 kgf',
                    Power_Output : '24 kVA',
                },
                {
                    Shaker_Model : 'SEV 300',
                    Amplifier_Model : 'DSA 32K',
                    System_Rating : '2500 kgf',
                    Power_Output : '32 kVA',
                },
                {
                    Shaker_Model : 'SEV 360	',
                    Amplifier_Model : 'DSA 36K',
                    System_Rating : '3000 kgf',
                    Power_Output : '36 kVA',
                },
                {
                    Shaker_Model : 'SEV 360	',
                    Amplifier_Model : 'DSA 45K',
                    System_Rating : '3500 kgf',
                    Power_Output : '45 kVA',
                },
                {
                    Shaker_Model : 'SEV 440',
                    Amplifier_Model : 'DSA 48K',
                    System_Rating : '4000 kgf',
                    Power_Output : '48 kVA',
                },
                {
                    Shaker_Model : 'SEV 440',
                    Amplifier_Model : 'DSA 56K',
                    System_Rating : '4800 kgf',
                    Power_Output : '56 kVA',
                },
                {
                    Shaker_Model : 'SEV 440',
                    Amplifier_Model : 'DSA 60K',
                    System_Rating : '5000 kgf',
                    Power_Output : '60 kVA',
                },
                {
                    Shaker_Model : 'SEV 440',
                    Amplifier_Model : 'DSA 80K',
                    System_Rating : '6000 kgf',
                    Power_Output : '80 kVA',
                },
                {
                    Shaker_Model : 'SEV 440A',
                    Amplifier_Model : 'DSA 60K',
                    System_Rating : '6000 kgf',
                    Power_Output : '60 kVA',
                },
                {
                    Shaker_Model : 'SEV 440A',
                    Amplifier_Model : 'DSA 80K',
                    System_Rating : '8000 kgf',
                    Power_Output : '80 kVA',
                },
            ],
            shead2 : 'Water Cooled Series',
            Shaker : [
                {
                    Shaker_Model : 'SEW 500',
                    Amplifier_Model : 'DSA 120K',
                    System_Rating : '7000 kgf',
                    Power_Output : '120 kVA',
                },
                {
                    Shaker_Model : 'SEW 500',
                    Amplifier_Model : 'DSA 160K',
                    System_Rating : '10000 kgf',
                    Power_Output : '160 kVA',
                },
                {
                    Shaker_Model : 'SEW 590',
                    Amplifier_Model : 'DSA 200K',
                    System_Rating : '13000 kgf',
                    Power_Output : '200 kVA',
                },
                {
                    Shaker_Model : 'SEW 590',
                    Amplifier_Model : 'DSA 240K',
                    System_Rating : '16000 kgf',
                    Power_Output : '240 kVA',
                },
                {
                    Shaker_Model : 'SEW 760',
                    Amplifier_Model : 'DSA 280K',
                    System_Rating : '29000 kgf',
                    Power_Output : '280 kVA',
                },
                {
                    Shaker_Model : 'SEW 760',
                    Amplifier_Model : 'DSA 320K',
                    System_Rating : '32000 kgf',
                    Power_Output : '320 kVA',
                },
            ],
        },
    },
    section3 = {
        heading: 'Notes:',
        li1: "Customised specifications are also tailored on request",
        li2: "Please contact Sdyn for advice on the optimum specifications to meet your testing requirements",
        li3: "Specifications are correct at the time of publication and are subject to improvement or amendment without prior notice",
    },
];