export const HEAD = [
    section1 = {
        heading : "Head Expander",
        desc : "A Shaker, in vertical orientation, operates in the Z axis. The diameter of the Shaker’s Armature is limited by the rating and design of the Shaker. Many times, the dimensions of the test object exceed the working area offered by an Armature. In order to increase the working area of an Armature, a Head Expander is used. We offer a varied range of Non-Guided and Guided Head Expanders, in circular and square shape, to meet requirements like testing large objects to testing multiple objects at the same time. Our Head Expanders are manufactured by welding magnesium alloy tool plates and treated with vibration dampening material to reduce peaks and harmonics. They are available in various shapes and sizes with customised hole patterns as per customer requirement.",
        shead1 : "Sdyn manufactures the following types of Head Expanders:",
        first : {
            heading : "Circular Head Expander",
            desc: "Shape of the head expander is circular. It is not support or guided externally. Any hole pattern can be provided as per customer requirement.",
        },
        second : {
            heading : "Square Head Expander",
            desc: "Shape of the head expander is square. It is not support or guided externally. Any hole pattern can be provided as per customer requirement.",
        },
        third : {
            heading : "Guided Head Expander",
            desc: "Guided Head Expander",
        }
    },
    section2 = {
        heading : 'Technical Specifications',
        table1 : {
            table_heading: {
                head1: 'Shaker Model',
                head2: 'CHE 030 (300 mm)',
                head3: 'CHE 040 (400 mm)',
                head4: 'CHE 060 (600 mm)',
                head5: 'CHE 080 (800 mm)',
            },
            shead : 'Circular Head Expander',
            Circular : [
                {
                    Shaker_Model : 'SEV 125',
                    CHE_030 : 'X',
                    CHE_040 : 'X',
                    CHE_060 : 'X',
                    CHE_080 : 'X',
                },
                {
                    Shaker_Model : 'SEV 140',
                    CHE_030 : '10 kg',
                    CHE_040 : '12 kg',
                    CHE_060 : 'X',
                    CHE_080 : 'X',
                },
                {
                    Shaker_Model : 'SEV 180',
                    CHE_030 : '12 kg',
                    CHE_040 : '14 kg',
                    CHE_060 : 'X',
                    CHE_080 : 'X',
                },
                {
                    Shaker_Model : 'SEV 240',
                    CHE_030 : 'X',
                    CHE_040 : '15 kg',
                    CHE_060 : '30 kg',
                    CHE_080 : 'X',
                },
                {
                    Shaker_Model : 'SEV 300',
                    CHE_030 : 'X',
                    CHE_040 : '16 kg',
                    CHE_060 : '32 kg',
                    CHE_080 : '58 kg',
                },
                {
                    Shaker_Model : 'SEV 360',
                    CHE_030 : 'X',
                    CHE_040 : 'X',
                    CHE_060 : '33 kg',
                    CHE_080 : '62 kg',
                },
                {
                    Shaker_Model : 'SEV 440',
                    CHE_030 : 'X',
                    CHE_040 : 'X',
                    CHE_060 : '35 kg',
                    CHE_080 : '64 kg',
                },
            ],
        },
        table2 : {
            table_heading: {
                head1: 'Shaker Model',
                head2: 'SHE 0303 (300 mm)',
                head3: 'SHE 0404 (400 mm)',
                head4: 'SHE 0606 (600 mm)',
                head5: 'SHE 0808 (800 mm)',
            },
            shead : 'Square Head Expander',
            Circular : [
                {
                    Shaker_Model : 'SEV 125',
                    CHE_0303 : 'X',
                    CHE_0404 : 'X',
                    CHE_0606 : 'X',
                    CHE_0808 : 'X',
                },
                {
                    Shaker_Model : 'SEV 140',
                    CHE_0303 : '12 kg',
                    CHE_0404 : '14 kg',
                    CHE_0606 : 'X',
                    CHE_0808 : 'X',
                },
                {
                    Shaker_Model : 'SEV 180',
                    CHE_0303 : '14 kg',
                    CHE_0404 : '16 kg',
                    CHE_0606 : 'X',
                    CHE_0808 : 'X',
                },
                {
                    Shaker_Model : 'SEV 240',
                    CHE_0303 : 'X',
                    CHE_0404 : '18 kg',
                    CHE_0606 : '36 kg',
                    CHE_0808 : 'X',
                },
                {
                    Shaker_Model : 'SEV 300',
                    CHE_0303 : 'X',
                    CHE_0404 : '20 kg',
                    CHE_0606 : '38 kg',
                    CHE_0808 : '74 kg',
                },
                {
                    Shaker_Model : 'SEV 360',
                    CHE_0303 : 'X',
                    CHE_0404 : 'X',
                    CHE_0606 : '40 kg',
                    CHE_0808 : '76 kg',
                },
                {
                    Shaker_Model : 'SEV 440',
                    CHE_0303 : 'X',
                    CHE_0404 : 'X',
                    CHE_0606 : '42 kg',
                    CHE_0808 : '78 kg',
                },
            ],
        },
        table3 : {
            table_heading: {
                head1: 'Shaker Model',
                head2: 'CHE 0303 (300 mm)',
                head3: 'CHE 0404 (400 mm)',
                head4: 'CHE 0606 (600 mm)',
                head5: 'CHE 0808 (800 mm)',
            },
            shead : 'Guided Head Expander (Square Sha',
            Circular : [
                {
                    Shaker_Model : 'SEV 125',
                    CHE_0303 : 'X',
                    CHE_0404 : 'X',
                    CHE_0606 : 'X',
                    CHE_0808 : 'X',
                },
                {
                    Shaker_Model : 'SEV 140',
                    CHE_0303 : 'X',
                    CHE_0404 : 'X',
                    CHE_0606 : 'X',
                    CHE_0808 : 'X',
                },
                {
                    Shaker_Model : 'SEV 180',
                    CHE_0303 : 'X',
                    CHE_0404 : 'X',
                    CHE_0606 : '26 kg',
                    CHE_0808 : 'X',
                },
                {
                    Shaker_Model : 'SEV 240',
                    CHE_0303 : 'X',
                    CHE_0404 : 'X',
                    CHE_0606 : '34 kg',
                    CHE_0808 : '68 kg',
                },
                {
                    Shaker_Model : 'SEV 300',
                    CHE_0303 : 'X',
                    CHE_0404 : 'X',
                    CHE_0606 : 'X',
                    CHE_0808 : '70 kg',
                },
                {
                    Shaker_Model : 'SEV 360',
                    CHE_0303 : 'X',
                    CHE_0404 : 'X',
                    CHE_0606 : 'X',
                    CHE_0808 : '72 kg',
                },
                {
                    Shaker_Model : 'SEV 440',
                    CHE_0303 : 'X',
                    CHE_0404 : 'X',
                    CHE_0606 : 'X',
                    CHE_0808 : 'X',
                },
            ],
        },
    },
    section3 = {
        heading: 'Notes:',
        li1: "Customised specifications are also tailored on request",
        li2: "Please contact Sdyn for advice on the optimum specifications to meet your testing requirements",
        li3: "Specifications are correct at the time of publication and are subject to improvement or amendment without prior notice",
    },
];