const CompanyDetail = {
    Heading : "hello",
    Links:[
      {
       msg1:"Envisys Technologies is promoted by Engineering and Management background professionals of more than forty years of cumulative experience in design, manufacture, marketing and service of environmental test chambers with an objective to offer high-quality products at competitive prices with ingenious design and strategy to reduce costs.",
       msg2:"Envisys is a leading environmental test chambers manufacturer and supplier based in Bangalore, India with over 40 years of diverse experience in designing environmental testing solutions. Since our commencement, we have developed products for reliability, performance, and ease-of-use, designed to meet our clients testing requirements and enhance the reliability and safety of their products. Our unique manufacturing & supplying expertise has been the foundation behind our success over the years. A key part of what we do is customizing complex environmental test chambers, and our team of engineers always remains at the forefront of technology when it comes to environmental test chamber application, building upon a solid knowledge base.",
       msg3:"We are always at the forefront when comes to espousing new testing technologies to streamline the testing process and offer an unparalleled testing experience to all of our clients. Our passion for innovation has remained constant during the four decades of existence. In our corporate strategy and operations, we have developed and imbibed a culture of innovation over the years. The environmental simulation test sector is extremely competitive, making it tough for businesses to stay afloat and differentiate themselves from their competitors. Envisys, on the other hand, can do so because of its dedication to manufacturing, supplying & innovation, which it realises through its dedicated R&D centre.This has led to our environmental test chamber products being widely used by several MNCs including Fortune 500 companies in Bangalore as well as across India such as Wipro, Bajaj, Bosch, Crompton Greaves, Akzo Nobel, Commscope, among others",
       msg4: "With our clients becoming more mindful about product reliability, we at Envisys believe incontinually pushing the quality and standards of our products. As a leading manufacturer and supplier of environmental test chambers in Bangalore, India, we customise our testing methodology to find any veiledpossibility of malfunctions in clients products. To conduct such customised testing requires a customised reliability test system and this is where Envisys has a strong foothold in Bangalore and across India.",
       msg5:"At Envisys, we go the extra mile to make sure our clients get the best-in-class experience from us. All through our journey to become one of the foremost brands of environmental testing solutions, we have stuck to our values and beliefs that “clients come first”. Our client-centric value is transforming from a manufacturer, supplier to a solution provider. Our zeal for excellence hasdriven us to attain unmatched quality while offering flawless post-sales services. Our environmental test chambers support and services have earned the reputation of being the only environmental test chambers company in Bangalore, India that responds to clients’ complaints within 24 hours.",
       msg6:"ABOUT ENVISYS",
       msg7:"Manufacturer & Service Provider of Environmental Test Chambers.",      
    },
     ] 
};

export default CompanyDetail;